### PR TITLE
Add Mimick sample

### PR DESCRIPTION
**Pull request by Epoque1**
- Adds sample code for the Mimick Fody framework

### CODE REVIEW

**Comment by Epoque1** [comment]
Ah yes, I had put them in a separate project initially but thought they might be bundled under the Samples project. I'll move them across now, and add the suppression on the warnings (again, this was working under the separate project.)

FYI, I'm unable to properly build the solution in VS2017 due to errors about the .NET Core version against the SDK version, as described:

image

**Comment by ltrzesniewski** [comment]
Looks like you just need to install the .NET Core 2.2 SDK.

**Comment by SimonCropp** [comment]
@ltrzesniewski the reason i have been recently favoring having multiple samples in one project is 

 * there are currently 50+ weavers. VS doesnt handle solutions with many projects. so maintaining that sln, and verifying it, was getting to be a pain
 * i have found that by mixing weavers in the same project tests to cause interaction bugs to surface.

Obviously some wavers are better with their project, eg costura which is more about packaging. and some samples are complex enough to warrant  their own project.

But for simple samples i am tending to group them

**Comment by ltrzesniewski** [comment]
Ok, I thought this one was complex enough. Sorry for suggesting doing it the wrong way.

**Comment by SimonCropp** [comment]
@ltrzesniewski dont apologize. i had not documented that decision. i will add it to the readme. @Epoque1 dont worry about merging in your sample. we will leave as is for not

**Comment by SimonCropp** [comment]
Thanks for this

**Pull request merged**
